# Generated by Django 5.2.8 on 2026-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allowedemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedemail',
            options={'verbose_name': '허용된 이메일', 'verbose_name_plural': '허용된 이메일'},
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='description',
            field=models.CharField(blank=True, help_text='이메일 사용자 메모', max_length=100),
        ),
    ]
