# Generated by Django 6.0.2 on 2026-07-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_allowedemail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedemail',
            options={'verbose_name': '가입 허용 이메일', 'verbose_name_plural': '가입 허용 이메일'},
        ),
    ]
