# Generated by Django 5.2.8 on 2026-02-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='계좌 별명 (예: 메인 투자계좌)', max_length=50)),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='계좌번호')),
                ('app_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '한투 계좌',
                'verbose_name_plural': '한투 계좌 목록',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='접근 토큰')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='발급 일시')),
                ('expired_at', models.DateTimeField(verbose_name='공식 만료 일시')),
                ('is_valid', models.BooleanField(default=True, verbose_name='유효 여부')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='investments.account')),
            ],
            options={
                'verbose_name': 'API 토큰',
                'verbose_name_plural': 'API 토큰 목록',
            },
        ),
    ]
