# Generated by Django 5.2.8 on 2026-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hts_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(help_text="'-'없이 10자리", max_length=20, unique=True, verbose_name='계좌번호'),
        ),
    ]
