# Generated by Django 5.2.8 on 2026-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_account_hts_id_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='token',
            name='is_use',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
    ]
