# Generated by Django 6.0.2 on 2026-07-12 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_remove_token_is_valid_token_is_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(help_text="'-'없이 10자리", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='계좌번호는 숫자 10자리여야 합니다.', regex='^\\d{10}$')], verbose_name='계좌번호'),
        ),
    ]
