# Generated by Django 6.0.2 on 2026-09-29 15:00

import investments.strategies
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_merge_token_into_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='strategy',
            field=models.CharField(blank=True, choices=investments.strategies.get_strategy_choices, default='', max_length=50, verbose_name='투자 전략'),
        ),
    ]
