"""
Django settings for adminPage project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import environ

# 1. 경로 설정 (settings/base.py 기준이므로 한 단계 더 올라가야 루트 폴더임)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

current_env_mode = os.getenv('DJANGO_SETTINGS_MODULE').split('.')[-1]  # local or prod

env = environ.Env()
# 공통 .env
env.read_env(os.path.join(BASE_DIR, '.env'))

# 환경별 env (.env.local or .env.prod)
specific_env = os.path.join(BASE_DIR, f'.env.{current_env_mode}')
if os.path.exists(specific_env):
    env.read_env(specific_env, overwrite=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # allauth # 로그인 관련
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # 만든 앱
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth # 로그인 관련
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'adminPage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adminPage.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# [구글 로그인 및 계정 설정]

# 1. 로그인 방식 설정 (경고 해결: 구버전 명칭 대신 최신 명칭 사용)
ACCOUNT_LOGIN_METHODS = {'email'}
# 2. 회원가입 시 필요한 필드 (* 필수)
ACCOUNT_SIGNUP_FIELDS = ['email*']
# 3. 버튼 누르자마자 구글 로그인 화면으로 바로 이동 (사용자 경험 개선)
SOCIALACCOUNT_LOGIN_ON_GET = True
# 4. 소셜 가입 시 추가 정보 입력창(Signup page) 건너뛰기
SOCIALACCOUNT_AUTO_SIGNUP = True
# 5. 이메일 확인 절차 생략 (가입 즉시 활성화)
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': env('GOOGLE_CLIENT_ID'),
            'secret': env('GOOGLE_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# 로그인 안 한 사용자가 로그인이 필요한 페이지에 접근했을 때 어디로 보낼 것인가
LOGIN_URL = '/accounts/login/'
# 로그인에 성공한 직후에 어디로 보낼 것인가
LOGIN_REDIRECT_URL = '/'
# 로그아웃 버튼을 눌러서 세션이 종료된 후 어디로 보낼 것인가
LOGOUT_REDIRECT_URL = '/accounts/login/'
# 로그아웃 버튼 클릭 시 "정말 로그아웃 하시겠습니까?" 페이지를 건너뛰고 싶다면 추가
ACCOUNT_LOGOUT_ON_GET = True

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if current_env_mode =='local':
    # [로컬] SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else :
    # [배포] MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': env('DATABASE_HOST'),  # 또는 '127.0.0.1'
            'PORT': env('DATABASE_PORT'),  # MySQL 기본 포트
            'USER': env('DATABASE_USER'),  # MySQL 유저네임 (보통 root)
            'PASSWORD': env('DATABASE_PASSWORD'),  # MySQL 비밀번호
            'NAME': env('DATABASE_NAME'),  # 생성한 데이터베이스 이름
            'CONN_MAX_AGE': 600,  # 10분 동안 커넥션 유지 (성능 향상)
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',  # 이모지 저장을 위해 권장
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 1. 언어 설정: 장고 관리자 페이지나 에러 메시지 등이 한국어로 나옵니다.
LANGUAGE_CODE = 'ko-kr'

# 2. 시간대 설정: 한국 표준시(KST)로 설정합니다.
TIME_ZONE = 'Asia/Seoul'

# 3. 국제화(i18n) 기능을 사용할지 여부
USE_I18N = True

# 4. 시간대 처리(TZ) 기능을 사용할지 여부
# True로 두면 내부적으로는 UTC로 저장하고 보여줄 때 KST로 변환해줍니다. (권장)
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 배포 시 collectstatic이 모이는 곳

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 사용자가 업로드한 파일(프로필 이미지 등) 저장소

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
